### ISSUE TITLE
problem in opel corsa E intellilink R4.0 infotainment

### ISSUE THREAD

**Issue by pascalgreece** [thekirankumar/carstream-android-auto#137]
i have the latest version, i have network connection, but when i connect it to my infotainment system it only shows “press the last icon in the bottom bar to start playing”. i tried everything, did just as in youtube instructed. but no luck. plus, while viewing in my smartphone, it doesn’t look like in photos or video, it has a totally different interface. no “send to car” option i.e. .any ideas?

**Comment by shmykelsa** [comment]
If you happen to have Android Auto 3.0, you should follow issue #116 or, alternatively, uninstall Android Auto, install version 2.9 or below, disable automatic updates, install the app by modifying the package name (APK Editor or App Cloner) and re-activate unknown sources

Plus, send to car option is no more available since there are bookmarks.

Remember that you have to launch the app from last icon on right, the one with sort of a speedometer

**Comment by pascalgreece** [comment]
package modification not needed, it worked with 2.9 AA. thanks.
